server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope:
              - openid

        provider:
          keycloak:
            issuer-uri: http://172.29.92.91:8443/realms/SpringBootKeycloak
#            issuer-uri: http://localhost:8180/realms/SpringBootKeycloak
            user-name-attribute: preferred_username

      resource-server:
        jwt:
#          issuer-uri: http://localhost:8180/realms/SpringBootKeycloak
#          jwk-set-uri: http://localhost:8180/realms/SpringBootKeycloak/protocol/openid-connect/certs
          issuer-uri: http://172.29.92.91:8443/realms/SpringBootKeycloak
          jwk-set-uri: http://172.29.92.91:8443/realms/SpringBootKeycloak/protocol/openid-connect/certs
